version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: pg-db
    env_file: .env
    ports:
      - "5433:5433"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    command: >
      postgres -c port=5433
    environment:
      - TZ=Europe/Moscow
      - LANG=C.UTF-8
    restart: unless-stopped
